# Generated by Django 4.1.4 on 2023-01-15 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subasta', to='auctions.listing'),
        ),
    ]
