# Generated by Django 4.1.4 on 2023-01-20 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bid_alter_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='available',
        ),
    ]
